apiVersion: v1
kind: ConfigMap
metadata:
  name: acs-auth-roles
  namespace: acs-rox
data:
  authroles.json: |
    [ "-k", "-u", "admin:$(ACS_ADMIN_PASSWORD)", "--header", "Content-Type: application/json", "-X", "POST", "$(CENTRAL)/v1/groupsbatch", "-d", "{\"previous_groups\":[],\"required_groups\":[{\"props\":{\"authProviderId\":\"38c7afcd-d943-4163-bdb0-7787f9cdb3a4\",\"key\": \"groups\", \"value\": \"Analyst_test5\"},\"roleName\":\"Analyst\"}]}" ]
