apiVersion: v1
kind: ConfigMap
metadata:
  name: acs-auth-roles
  namespace: acs-rox
  annotations:
    owner: philmoses
data:
  authroles.json: |
     {\"previous_groups\":[],\"required_groups\":[{\"props\":{\"authProviderId\":\"38c7afcd-d943-4163-bdb0-7787f9cdb3a4\",\"key\": \"groups\", \"value\": \"Analyst_test5\"},\"roleName\":\"Analyst\"}]} 
