apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  generation: 1
  name: stackrox-secured-cluster-services
  namespace: acs-rox
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  admissionControl:
    bypass: BreakGlassAnnotation
    contactImageScanners: DoNotScanInline
    listenOnCreates: true
    listenOnEvents: true
    listenOnUpdates: true
    timeoutSeconds: 20
  auditLogs:
    collection: Auto
  clusterName: my-cluster
  perNode:
    collector:
      collection: KernelModule
      imageFlavor: Regular
    taintToleration: TolerateTaints
  scanner:
    analyzer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
    scannerComponent: AutoSense
