apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  finalizers:
    - uninstall-helm-release
  name: stackrox-central-services
  namespace: acs-rox
spec:
  central:
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
        size: 20Gi
        storageClassName: pmo1
  egress:
    connectivityPolicy: Online
  scanner:
    analyzer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 3
        minReplicas: 1
        replicas: 1
    scannerComponent: Enabled
